// Code generated by "stringer -trimprefix battery -type BatteryStatusType"; DO NOT EDIT.

package ptouchgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[batteryFull-0]
	_ = x[batteryHalf-1]
	_ = x[batteryLow-2]
	_ = x[batteryChangeBatteries-3]
	_ = x[batteryAC-4]
}

const _BatteryStatusType_name = "FullHalfLowChangeBatteriesAC"

var _BatteryStatusType_index = [...]uint8{0, 4, 8, 11, 26, 28}

func (i BatteryStatusType) String() string {
	if i < 0 || i >= BatteryStatusType(len(_BatteryStatusType_index)-1) {
		return "BatteryStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BatteryStatusType_name[_BatteryStatusType_index[i]:_BatteryStatusType_index[i+1]]
}
