// Code generated by "stringer -trimprefix fontColor -type FontColor"; DO NOT EDIT.

package ptouchgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fontColorWhite-1]
	_ = x[fontColorRed-4]
	_ = x[fontColorBlue-5]
	_ = x[fontColorBlack-8]
	_ = x[fontColorGold-10]
	_ = x[fontColorFBlue-98]
	_ = x[fontColorCleaning-240]
	_ = x[fontColorStencil-241]
	_ = x[fontColorOther-2]
	_ = x[fontColorInvalid-255]
}

const (
	_FontColor_name_0 = "WhiteOther"
	_FontColor_name_1 = "RedBlue"
	_FontColor_name_2 = "Black"
	_FontColor_name_3 = "Gold"
	_FontColor_name_4 = "FBlue"
	_FontColor_name_5 = "CleaningStencil"
	_FontColor_name_6 = "Invalid"
)

var (
	_FontColor_index_0 = [...]uint8{0, 5, 10}
	_FontColor_index_1 = [...]uint8{0, 3, 7}
	_FontColor_index_5 = [...]uint8{0, 8, 15}
)

func (i FontColor) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FontColor_name_0[_FontColor_index_0[i]:_FontColor_index_0[i+1]]
	case 4 <= i && i <= 5:
		i -= 4
		return _FontColor_name_1[_FontColor_index_1[i]:_FontColor_index_1[i+1]]
	case i == 8:
		return _FontColor_name_2
	case i == 10:
		return _FontColor_name_3
	case i == 98:
		return _FontColor_name_4
	case 240 <= i && i <= 241:
		i -= 240
		return _FontColor_name_5[_FontColor_index_5[i]:_FontColor_index_5[i+1]]
	case i == 255:
		return _FontColor_name_6
	default:
		return "FontColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
