// Code generated by "stringer -linecomment -type MediaType"; DO NOT EDIT.

package ptouchgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mediaTypeNone-0]
	_ = x[mediaTypeLaminated-1]
	_ = x[mediaTypeNonLaminated-3]
	_ = x[mediaTypeHeatShirink-17]
	_ = x[mediaTypeInvalid-255]
}

const (
	_MediaType_name_0 = "No tapeLaminated"
	_MediaType_name_1 = "Non laminated"
	_MediaType_name_2 = "Heat shrink tube"
	_MediaType_name_3 = "Invalid tape type"
)

var (
	_MediaType_index_0 = [...]uint8{0, 7, 16}
)

func (i MediaType) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _MediaType_name_0[_MediaType_index_0[i]:_MediaType_index_0[i+1]]
	case i == 3:
		return _MediaType_name_1
	case i == 17:
		return _MediaType_name_2
	case i == 255:
		return _MediaType_name_3
	default:
		return "MediaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
