// Code generated by "stringer -trimprefix notification -type Notification"; DO NOT EDIT.

package ptouchgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[notificationInvalid-0]
	_ = x[notificationCoverOpen-1]
	_ = x[notificationCoverClose-2]
}

const _Notification_name = "InvalidCoverOpenCoverClose"

var _Notification_index = [...]uint8{0, 7, 16, 26}

func (i Notification) String() string {
	if i < 0 || i >= Notification(len(_Notification_index)-1) {
		return "Notification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Notification_name[_Notification_index[i]:_Notification_index[i+1]]
}
