// Code generated by "stringer -trimprefix phaseNumber -type PhaseNumber"; DO NOT EDIT.

package ptouchgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[phaseNumberEdit-0]
	_ = x[phaseNumberEditFeed-1]
	_ = x[phaseNumberNormal-0]
	_ = x[phaseNumberNormalCoverOpen-20]
}

const (
	_PhaseNumber_name_0 = "EditEditFeed"
	_PhaseNumber_name_1 = "NormalCoverOpen"
)

var (
	_PhaseNumber_index_0 = [...]uint8{0, 4, 12}
)

func (i PhaseNumber) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _PhaseNumber_name_0[_PhaseNumber_index_0[i]:_PhaseNumber_index_0[i+1]]
	case i == 20:
		return _PhaseNumber_name_1
	default:
		return "PhaseNumber(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
