// Code generated by "stringer -trimprefix phaseType -type PhaseTypeNumber"; DO NOT EDIT.

package ptouchgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[phaseTypeEdit-0]
	_ = x[phaseTypeNormal-1]
}

const _PhaseTypeNumber_name = "EditNormal"

var _PhaseTypeNumber_index = [...]uint8{0, 4, 10}

func (i PhaseTypeNumber) String() string {
	if i < 0 || i >= PhaseTypeNumber(len(_PhaseTypeNumber_index)-1) {
		return "PhaseTypeNumber(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhaseTypeNumber_name[_PhaseTypeNumber_index[i]:_PhaseTypeNumber_index[i+1]]
}
