// Code generated by "stringer -trimprefix phaseNumber -type PhaseNumber"; DO NOT EDIT.

package ptouchgo

import "strconv"

const (
	_PhaseNumber_name_0 = "EditEditFeed"
	_PhaseNumber_name_1 = "NormalCoverOpen"
)

var (
	_PhaseNumber_index_0 = [...]uint8{0, 4, 12}
)

func (i PhaseNumber) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _PhaseNumber_name_0[_PhaseNumber_index_0[i]:_PhaseNumber_index_0[i+1]]
	case i == 20:
		return _PhaseNumber_name_1
	default:
		return "PhaseNumber(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
