// Code generated by "stringer -linecomment -type StatusType"; DO NOT EDIT.

package ptouchgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[statusTypeReply-0]
	_ = x[statusTypePrintingCompleted-1]
	_ = x[statusTypeErrorOccured-2]
	_ = x[statusTypeIFModeFinished-3]
	_ = x[statusTypePowerOff-4]
	_ = x[statusTypeNotification-5]
	_ = x[statusTypePhaseChange-6]
}

const _StatusType_name = "ReplyPrinting completedError occuredIFModeFinished(unused)Power offNotificationPhase change"

var _StatusType_index = [...]uint8{0, 5, 23, 36, 58, 67, 79, 91}

func (i StatusType) String() string {
	if i < 0 || i >= StatusType(len(_StatusType_index)-1) {
		return "StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusType_name[_StatusType_index[i]:_StatusType_index[i+1]]
}
