// Code generated by "stringer -linecomment -type StatusType"; DO NOT EDIT.

package ptouchgo

import "strconv"

const _StatusType_name = "ReplyPrinting completedError occuredIFModeFinished(unused)Power offNotificationPhase change"

var _StatusType_index = [...]uint8{0, 5, 23, 36, 58, 67, 79, 91}

func (i StatusType) String() string {
	if i < 0 || i >= StatusType(len(_StatusType_index)-1) {
		return "StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusType_name[_StatusType_index[i]:_StatusType_index[i+1]]
}
