// Code generated by "stringer -linecomment -type TapeWidth"; DO NOT EDIT.

package ptouchgo

import "strconv"

const (
	_TapeWidth_name_0 = "No tape"
	_TapeWidth_name_1 = "3.5mm"
	_TapeWidth_name_2 = "6mm"
	_TapeWidth_name_3 = "9mm"
	_TapeWidth_name_4 = "12mm"
	_TapeWidth_name_5 = "18mm"
	_TapeWidth_name_6 = "24mm"
)

func (i TapeWidth) String() string {
	switch {
	case i == 0:
		return _TapeWidth_name_0
	case i == 4:
		return _TapeWidth_name_1
	case i == 6:
		return _TapeWidth_name_2
	case i == 9:
		return _TapeWidth_name_3
	case i == 12:
		return _TapeWidth_name_4
	case i == 18:
		return _TapeWidth_name_5
	case i == 24:
		return _TapeWidth_name_6
	default:
		return "TapeWidth(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
